### ISSUE TITLE
两个在线资源，本地下载改了路径还是没用

### ISSUE THREAD

**Issue by ziyoo365** [cxumol/tg-search#1]
打开home.html后显示不正常，弄了很久都不行，难道代码加密了？

**Comment by cxumol** [comment]
我这里实测可以离线运行｡  

![image](https://user-images.githubusercontent.com/8279655/50073242-d7daca00-018c-11e9-9d89-0c7946a3403c.png)

注意, 加载 fontawesome 的资源稍微麻烦一点, 
除了本来的 css 文件外, 请参考 [这篇答疑](https://stackoverflow.com/a/43635286),  到 [官网此处](https://fontawesome.com/how-to-use/on-the-web/setup/hosting-font-awesome-yourself) 下载资源包｡  
然后将资源包的 webfonts 文件夹囫囵拷到 ChatExport 下面, 即,  `ChatExport_dd_mm_yyyy/webfonts`, 就可以了｡ 

jquery 就没这么多弯弯绕绕了｡ 

"代码加密", 不懂在说什么. 难道指的是, 文本编辑器打开 jquery.js / fontawesome.css 发现是乱码? 我用 [这个下载器](https://github.com/iawia002/annie) 下载来确实是乱码, 但用 curl 下载到的文件是正常的｡ 

所以, 如果你发现下载到的在线资源, 文本编辑器打开, 出现乱码/二进制数字, 最稳的办法是用浏览器打开, 复制所有内容, 然后本地新建同名文件, 粘贴进去｡

**Comment by cxumol** [comment]
[当前版本](https://github.com/cxumol/tg-search/releases/tag/lite0.2) 已无需加载在线资源
