### ISSUE TITLE
不用那么麻烦

### ISSUE THREAD

**Issue by siaimes** [cxumol/tg-search#3]
notepad++搜索文件夹就行了呗！

**Comment by cxumol** [comment]
没错。即使没装 notepad++ (比如我)，也可以用其它文本编辑器搜索文件夹。
不过考虑到这样做，有点增加技术门槛，应该需要脑补 HTML。不想脑补的、就用这个咯。

**Comment by MizunaRei** [comment]
来个定制客户端，一键导出并搜索。
